// Generated by scripts/generate-pet-subject-framing.mjs.
// Do not hand-edit: these measurements keep every transparent pet canvas
// aligned to the same visible subject height and floor line.

export type PetSubjectFraming = {
  centerX: number;
  feetY: number;
  subjectHeight: number;
  subjectWidth: number;
};

const PET_SUBJECT_FRAMING: Readonly<Record<string, PetSubjectFraming>> = {
  "breed:cat:abyssinian": { centerX: 0.463028, feetY: 0.869447, subjectHeight: 0.748104, subjectWidth: 0.705399 },
  "breed:cat:american-shorthair": { centerX: 0.497653, feetY: 0.829361, subjectHeight: 0.646804, subjectWidth: 0.699531 },
  "breed:cat:bengal": { centerX: 0.483587, feetY: 0.826464, subjectHeight: 0.671909, subjectWidth: 0.664713 },
  "breed:cat:birman": { centerX: 0.481808, feetY: 0.818527, subjectHeight: 0.640845, subjectWidth: 0.855634 },
  "breed:cat:bombay": { centerX: 0.458333, feetY: 0.821235, subjectHeight: 0.565005, subjectWidth: 0.688967 },
  "breed:cat:british-shorthair": { centerX: 0.471244, feetY: 0.799025, subjectHeight: 0.494583, subjectWidth: 0.679577 },
  "breed:cat:burmese": { centerX: 0.493545, feetY: 0.834236, subjectHeight: 0.48104, subjectWidth: 0.585681 },
  "breed:cat:devon-rex": { centerX: 0.5, feetY: 0.858613, subjectHeight: 0.719393, subjectWidth: 0.640845 },
  "breed:cat:domestic-longhair": { centerX: 0.469484, feetY: 0.838028, subjectHeight: 0.586132, subjectWidth: 0.798122 },
  "breed:cat:domestic-shorthair": { centerX: 0.453052, feetY: 0.827194, subjectHeight: 0.566089, subjectWidth: 0.690141 },
  "breed:cat:exotic-shorthair": { centerX: 0.470657, feetY: 0.79415, subjectHeight: 0.469664, subjectWidth: 0.673709 },
  "breed:cat:maine-coon": { centerX: 0.482981, feetY: 0.77856, subjectHeight: 0.62588, subjectWidth: 0.836854 },
  "breed:cat:munchkin": { centerX: 0.501174, feetY: 0.810943, subjectHeight: 0.611051, subjectWidth: 0.734742 },
  "breed:cat:norwegian-forest-cat": { centerX: 0.492958, feetY: 0.820693, subjectHeight: 0.659805, subjectWidth: 0.887324 },
  "breed:cat:oriental-shorthair": { centerX: 0.504695, feetY: 0.879198, subjectHeight: 0.745937, subjectWidth: 0.673709 },
  "breed:cat:persian": { centerX: 0.479484, feetY: 0.765727, subjectHeight: 0.559111, subjectWidth: 0.846424 },
  "breed:cat:ragdoll": { centerX: 0.485346, feetY: 0.770607, subjectHeight: 0.569957, subjectWidth: 0.837046 },
  "breed:cat:russian-blue": { centerX: 0.477113, feetY: 0.83857, subjectHeight: 0.657638, subjectWidth: 0.742958 },
  "breed:cat:savannah": { centerX: 0.554577, feetY: 0.859155, subjectHeight: 0.60455, subjectWidth: 0.611502 },
  "breed:cat:scottish-fold": { centerX: 0.500586, feetY: 0.735358, subjectHeight: 0.52603, subjectWidth: 0.656506 },
  "breed:cat:siamese": { centerX: 0.465376, feetY: 0.842904, subjectHeight: 0.710726, subjectWidth: 0.642019 },
  "breed:cat:siberian": { centerX: 0.537559, feetY: 0.858613, subjectHeight: 0.604009, subjectWidth: 0.868545 },
  "breed:cat:sphynx": { centerX: 0.484597, feetY: 0.792807, subjectHeight: 0.636071, subjectWidth: 0.611374 },
  "breed:dog:akita": { centerX: 0.436033, feetY: 0.818527, subjectHeight: 0.542254, subjectWidth: 0.660798 },
  "breed:dog:alaskan-malamute": { centerX: 0.456573, feetY: 0.843987, subjectHeight: 0.576923, subjectWidth: 0.720657 },
  "breed:dog:australian-shepherd": { centerX: 0.5, feetY: 0.875948, subjectHeight: 0.71831, subjectWidth: 0.666667 },
  "breed:dog:basset-hound": { centerX: 0.591549, feetY: 0.7974, subjectHeight: 0.45883, subjectWidth: 0.699531 },
  "breed:dog:beagle": { centerX: 0.511137, feetY: 0.787961, subjectHeight: 0.638286, subjectWidth: 0.616647 },
  "breed:dog:belgian-malinois": { centerX: 0.551643, feetY: 0.863489, subjectHeight: 0.612676, subjectWidth: 0.605634 },
  "breed:dog:bernese-mountain-dog": { centerX: 0.5, feetY: 0.866197, subjectHeight: 0.739437, subjectWidth: 0.671362 },
  "breed:dog:bichon-frise": { centerX: 0.502347, feetY: 0.789274, subjectHeight: 0.377031, subjectWidth: 0.725352 },
  "breed:dog:border-collie": { centerX: 0.576202, feetY: 0.768438, subjectHeight: 0.601952, subjectWidth: 0.756155 },
  "breed:dog:boston-terrier": { centerX: 0.497066, feetY: 0.80065, subjectHeight: 0.48104, subjectWidth: 0.653756 },
  "breed:dog:boxer": { centerX: 0.501761, feetY: 0.866739, subjectHeight: 0.738353, subjectWidth: 0.679577 },
  "breed:dog:bulldog": { centerX: 0.499413, feetY: 0.830444, subjectHeight: 0.608342, subjectWidth: 0.768779 },
  "breed:dog:cane-corso": { centerX: 0.507629, feetY: 0.85428, subjectHeight: 0.590466, subjectWidth: 0.585681 },
  "breed:dog:cavalier-king-charles-spaniel": { centerX: 0.505869, feetY: 0.827194, subjectHeight: 0.60455, subjectWidth: 0.692488 },
  "breed:dog:chihuahua": { centerX: 0.563892, feetY: 0.771692, subjectHeight: 0.614967, subjectWidth: 0.745604 },
  "breed:dog:chow-chow": { centerX: 0.547535, feetY: 0.84182, subjectHeight: 0.555796, subjectWidth: 0.726526 },
  "breed:dog:dachshund": { centerX: 0.498826, feetY: 0.74052, subjectHeight: 0.511376, subjectWidth: 0.633803 },
  "breed:dog:dalmatian": { centerX: 0.576291, feetY: 0.821777, subjectHeight: 0.518418, subjectWidth: 0.610329 },
  "breed:dog:dobermann": { centerX: 0.484742, feetY: 0.875406, subjectHeight: 0.778982, subjectWidth: 0.539906 },
  "breed:dog:english-cocker-spaniel": { centerX: 0.508216, feetY: 0.811484, subjectHeight: 0.453413, subjectWidth: 0.788732 },
  "breed:dog:french-bulldog": { centerX: 0.523447, feetY: 0.7782, subjectHeight: 0.587852, subjectWidth: 0.638921 },
  "breed:dog:german-shepherd": { centerX: 0.594484, feetY: 0.810943, subjectHeight: 0.664139, subjectWidth: 0.735915 },
  "breed:dog:golden-retriever": { centerX: 0.521714, feetY: 0.79415, subjectHeight: 0.645179, subjectWidth: 0.632629 },
  "breed:dog:great-dane": { centerX: 0.572098, feetY: 0.840564, subjectHeight: 0.732646, subjectWidth: 0.66354 },
  "breed:dog:greyhound": { centerX: 0.565141, feetY: 0.842362, subjectHeight: 0.562297, subjectWidth: 0.538732 },
  "breed:dog:havanese": { centerX: 0.497066, feetY: 0.818527, subjectHeight: 0.408992, subjectWidth: 0.841549 },
  "breed:dog:jack-russell-terrier": { centerX: 0.504108, feetY: 0.829902, subjectHeight: 0.581798, subjectWidth: 0.529343 },
  "breed:dog:labrador-retriever": { centerX: 0.515864, feetY: 0.817542, subjectHeight: 0.630211, subjectWidth: 0.622797 },
  "breed:dog:maltese": { centerX: 0.505282, feetY: 0.832611, subjectHeight: 0.522752, subjectWidth: 0.735915 },
  "breed:dog:miniature-schnauzer": { centerX: 0.499413, feetY: 0.864572, subjectHeight: 0.666306, subjectWidth: 0.672535 },
  "breed:dog:papillon": { centerX: 0.454812, feetY: 0.820693, subjectHeight: 0.495125, subjectWidth: 0.796948 },
  "breed:dog:pembroke-welsh-corgi": { centerX: 0.499414, feetY: 0.764642, subjectHeight: 0.56128, subjectWidth: 0.63306 },
  "breed:dog:pomeranian": { centerX: 0.545135, feetY: 0.763557, subjectHeight: 0.559111, subjectWidth: 0.825322 },
  "breed:dog:poodle-toy": { centerX: 0.500587, feetY: 0.830986, subjectHeight: 0.491874, subjectWidth: 0.515258 },
  "breed:dog:pug": { centerX: 0.5, feetY: 0.832069, subjectHeight: 0.553088, subjectWidth: 0.71831 },
  "breed:dog:rottweiler": { centerX: 0.495305, feetY: 0.844529, subjectHeight: 0.715601, subjectWidth: 0.652582 },
  "breed:dog:samoyed": { centerX: 0.578143, feetY: 0.810708, subjectHeight: 0.646836, subjectWidth: 0.80376 },
  "breed:dog:shiba-inu": { centerX: 0.5551, feetY: 0.777115, subjectHeight: 0.569414, subjectWidth: 0.660023 },
  "breed:dog:shih-tzu": { centerX: 0.502347, feetY: 0.823402, subjectHeight: 0.524919, subjectWidth: 0.762911 },
  "breed:dog:siberian-husky": { centerX: 0.579812, feetY: 0.788732, subjectHeight: 0.627844, subjectWidth: 0.741784 },
  "breed:dog:standard-poodle": { centerX: 0.507629, feetY: 0.847237, subjectHeight: 0.722102, subjectWidth: 0.606808 },
  "breed:dog:west-highland-white-terrier": { centerX: 0.503521, feetY: 0.806067, subjectHeight: 0.453954, subjectWidth: 0.530516 },
  "breed:dog:yorkshire-terrier": { centerX: 0.496479, feetY: 0.825569, subjectHeight: 0.67714, subjectWidth: 0.704225 },
  "pet:luna": { centerX: 0.502347, feetY: 0.704767, subjectHeight: 0.514085, subjectWidth: 0.617371 },
  "pet:milo": { centerX: 0.521714, feetY: 0.79415, subjectHeight: 0.645179, subjectWidth: 0.632629 },
};

export const PET_SUBJECT_FRAMING_KEYS = Object.freeze(
  Object.keys(PET_SUBJECT_FRAMING),
);

const DEFAULT_FRAMING: PetSubjectFraming = {
  centerX: 0.5,
  feetY: 0.8,
  subjectHeight: 0.64,
  subjectWidth: 0.64,
};

export function resolvePetSubjectFraming(key: string): PetSubjectFraming {
  return PET_SUBJECT_FRAMING[key] ?? DEFAULT_FRAMING;
}
